server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://101.34.85.209:3306/trashtests?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: trashtests
    password: Aa123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.refuse.entity